Make bash compatible, aiming for posix compliance.

diff --git a/bin/dick b/bin/dick
--- a/bin/dick
+++ b/bin/dick
@@ -1,6 +1,4 @@
-#!/usr/bin/env zsh
-typeset -A _dick_features
-declare -A _dick_memory
+#!/bin/sh
 _dick_hand=0
 
 _longdick_allowed_variable_names="johnson dick cock schlong penis dong"
@@ -14,16 +12,17 @@ _dick_value() {
         echo $value
         return
     fi
-    echo $_dick_memory["$1"]
+    eval "echo \$_dick_memory_${1}"
 }
 
 ## helper function to parse extract HEREDOC and
 ## de-indent to ensure an inner `EOF` does not
 ## have preceeding spaces. 
 _parse_heredoc_block() {
-    local raw=$(cat)
-    local ident=`echo $raw | head -n 1 | sed -n 's/^\([[:space:]]*\).*/\1/p'`
-    echo $raw | sed "s/^$ident//"
+    local raw ident
+    raw=$(cat)                # Grab the entire input
+    ident=$(printf '%s\n' "$raw" | head -n 1 | sed -n 's/^\([[:space:]]*\).*/\1/p')
+    printf '%s\n' "$raw" | sed "s/^$ident//"
 }
 
 # DICK <name> <value>
@@ -33,7 +32,15 @@ _parse_heredoc_block() {
 # @param $2 {string | numeric} value to assign. May be a variable name or Dick numeric literal.
 DICK() {
     local value=$(_dick_value $2)
-    _dick_memory["$1"]=$value
+    eval "_dick_memory_${1}=\"${value}\""
+}
+
+# RELEASE <name> <value>
+# 
+# Assign a value of Hand to a <name> in memory.
+# @param $1 {string} name of variable.
+RELEASE() {
+    eval "_dick_memory_${1}=\"${_dick_hand}\""
 }
 
 # GRIP <prompt>
@@ -59,14 +66,6 @@ GRIP() {
 # @param $1 {string | numeric} value to assign. May be a variable name or Dick numeric literal.
 GRAB() {
     _dick_hand=$(_dick_value $1)
-}
-
-# RELEASE <name> <value>
-# 
-# Assign a value of Hand to a <name> in memory.
-# @param $1 {string} name of variable.
-RELEASE() {
-    _dick_memory["$1"]=$_dick_hand
 }
 
 # LONDICK <value>
@@ -199,8 +198,11 @@ BAG() {
     local block=$(_parse_heredoc_block)
 
     shift
-    for ((i=1; i <= $#; i++)); do
-        block="${block//${@[$i]}/\$$i}"
+    i=1
+    while [ "$i" -le "$#" ]; do
+        eval "arg=\${$i}"
+        block=$(printf "%s" "$block" | sed "s/${arg}/\$$i/g")
+        i=$((i + 1))
     done
 
     eval "$name(){;$block;}"
@@ -311,10 +313,11 @@ __prepocess_long_dick() {
       | sed 's/DICK JOKES ARE IMMATURE, SERIOUSLY/CUM/g' \
       | sed -E 's/COCK GO FAST IF (.+)\!/__long_dick_loop \1 <<CUM/g' \
       | sed 's/ALRIGHT, STOP COCKING AROUND/CUM/g'
+    echo
 }
 
 __longdick_validate_variable_names() {
-    if [[ "$_dick_features[strict-mode]" != "true" ]]; then
+    if [[ ! "$_dick_features_enabled" =~ "strict-mode" ]]; then
         return 0
     fi
 
@@ -327,23 +330,31 @@ __longdick_validate_variable_names() {
     local last_location=""
     while IFS= read -r line; do
         ((++line_no))
-        if [[ "$line" =~ ^(DICK|RELEASE)\ ([^ ]+)(\ +.+)?$ ]]; then
-            local opcode="${match[1]}"
-            local name="${match[2]}"
-            local spaces="${opcode//?/ } "
+        local indent=`echo "$line" | sed -n 's/^\([[:space:]]*\).*/\1/p'`
+        set -- `echo $line | sed "s/^$ident//"`
+        local opcode="$1"
+        local name="$2"
+        local value="$3"
+        local spaces="${indent}${opcode//?/ } "
+
+        local col_no=$(($(echo "$spaces" | grep -o " " | wc -l) + 1))
+        local location="$(printf %02d:%02d "$line_no" "$col_no")"
+
+        if [[ "$line" == "${indent}DICK JOKES ARE IMMATURE, SERIOUSLY" ]]; then
+            :
+        elif [[ "$opcode" != "DICK" ]] && [[ "$opcode" != "RELEASE" ]]; then
+            :
+        elif [[ ! "$_longdick_allowed_variable_names" =~ "$name" ]]; then
             local hint="${name//?/^} "
-            local col_no=$(($(echo "$spaces" | grep -o " " | wc -l) + 1))
-            local location="$(printf %02d:%02d "$line_no" "$col_no")"
-            if [[ ! "$_longdick_allowed_variable_names" =~ "$name" ]]; then
-                echo -e "${_CLR_RED}[ERROR] Invalid variable name '$name' at $file_name:$location${_CLR_RST}" >&2
-                echo "${_CLR_RED}    ...${_CLR_RST} $last_line" >&2
-                echo "${_CLR_RED}    ...${_CLR_RST} $line" >&2
-                echo "        $spaces${_CLR_RED}$hint${_CLR_RST}" >&2
-                echo "        variable '$name' is not one of '$_longdick_allowed_variable_names'" >&2
-                echo >&2
-                exit_code=1
-            fi
+            echo "${_CLR_RED}[ERROR] Invalid variable name '$name' at $file_name:$location${_CLR_RST}" >&2
+            echo "${_CLR_RED}    ...${_CLR_RST} $last_line" >&2
+            echo "${_CLR_RED}    ...${_CLR_RST} $line" >&2
+            echo "        $spaces${_CLR_RED}$hint${_CLR_RST}" >&2
+            echo "        variable '$name' is not one of '$_longdick_allowed_variable_names'" >&2
+            echo >&2
+            exit_code=1
         fi
+
         last_line="$line"
         last_location="$location"
     done < "$file_name"
@@ -351,46 +362,57 @@ __longdick_validate_variable_names() {
     [[ $exit_code -ne 0 ]] && exit $exit_code
 }
 
-typeset -A _dick_default_features=(
-  shebang-args      true
-  strict-mode       false
-  help              false
-  exec              true
-)
-typeset -A _dick_help_text=(
-  shebang-args      "reading arguments from shebang"
-  strict-mode       "strict mode; limit to permitted variable names in LongDick."
-  help              "show this help"
-  exec              "execute after pre-processing."
-)
-typeset -A _dick_args_alias=(
-  -s                    strict-mode
-  --strict              strict-mode
-  --strict-mode         strict-mode
-  -h                    help
-  --help                help
-)
-typeset -A _dick_alias_only=(
-    help                true
-)
+_dick_features_available="strict-mode shebang-args exec help"
+_dick_features_default_enabled="shebang-args exec"
+_dick_features_enabled="$_dick_features_default_enabled"
 
-_dick_features=("${(@kv)_dick_default_features}")
+
+_dick_help_text_shebang_args="reading arguments from shebang"
+_dick_help_text_exec="execute after pre-processing."
+
+_dick_help_text_strict_mode="strict mode; limit to permitted variable names in LongDick."
+_dick_args_alias_strict_mode="--strict --strict-mode -s "
+
+_dick_help_text_help="show this help"
+_dick_args_alias_help="--help -h "
+_dick_alias_only_help=true
 
 _dick_source_filename=""
 _dick_show_help=false
+
+_enable_feature() {
+    if [[ ! "$_dick_features_available" =~ "$1" ]]; then
+        return
+    fi
+    if [[ "$_dick_features_enabled" =~ "$1" ]]; then
+        return
+    fi
+    _dick_features_enabled="${_dick_features_enabled} ${1}"
+}
+
+_disable_feature() {
+    if [[ ! "$_dick_features_available" =~ "$1" ]]; then
+        return
+    fi
+    if [[ ! "$_dick_features_enabled" =~ "$1" ]]; then
+        return
+    fi
+    _dick_features_enabled="${_dick_features_enabled/$1/}"
+}
 
 __dick_parse_args() {
     while [[ "$#" -gt 0 ]]; do
         arg="$1"
         case $arg in
-        --use-*) _dick_features[${1/--use-/}]=true; shift;;
-        --no-*) _dick_features[${1/--no-/}]=false; shift;;
-        -h|--help) _dick_features[help]=true; shift ;;
+        --use-*) _enable_feature "${1/--use-/}"; shift;;
+        --no-*) _disable_feature "${1/--no-/}"; shift;;
+        -h|--help) _enable_feature help; shift;;
+        -s|--strict|--strict-mode) _enable_feature strict-mode; shift;;
         *)
             if [[ -f "$1" ]]; then
                 _dick_source_filename="$1"
-            elif [[ "$_dick_default_features[$_dick_args_alias[$1]]" == "false" ]]; then
-                _dick_features[$_dick_args_alias[$1]]=true
+            elif [[ ! -z "$(eval "echo \$_dick_args_alias_${1/-/_}")" ]]; then
+                 _enable_feature "$(eval "echo \$_dick_args_alias_${1/-/_}")"
             fi
             shift
             ;;
@@ -400,14 +422,15 @@ __dick_parse_args() {
 
 __dick_parse_args $@
 
-if [[ "$_dick_features[help]" != "true" ]] && [[ -f $_dick_source_filename ]]; then
-    if [[ "$_dick_features[shebang-args]" == "true" ]]; then
+if [[ ! "$_dick_features_enabled" =~ "help" ]] && [[ -f $_dick_source_filename ]]; then
+    if [[ "$_dick_features_enabled" =~ "shebang-args" ]]; then
         __dick_parse_args $(head -n 1 "$_dick_source_filename")
     fi
     __longdick_validate_variable_names "$_dick_source_filename"
 
-    if [[ "$_dick_features[exec]" == "true" ]]; then
-    source <(__prepocess_long_dick "$_dick_source_filename")
+    if [[ "$_dick_features_enabled" =~ "exec" ]]; then
+        # source <(__prepocess_long_dick "$_dick_source_filename")
+        eval "$(__prepocess_long_dick "$_dick_source_filename")"
     else
         __prepocess_long_dick "$_dick_source_filename"
     fi
@@ -415,31 +438,32 @@ else
     echo "Usage: dick [options] program.dick"
     echo
     echo "Options:"
-    for key in "${(@k)_dick_help_text}"; do
-        local is_default=""
-        local line_desc=""
-        local desc="$_dick_help_text[$key]"
-        local indent=""
-        if [[ "${_dick_default_features[$key]}" == "true" ]]; then
+    for key in $_dick_features_available; do
+        is_default=""
+        line_desc=""
+        desc="$(eval "echo \$_dick_help_text_${key/-/_}")"
+        
+        indent=""
+        if [[ "$_dick_features_default_enabled" =~ "$key" ]]; then
             printf "  --no-%-21s %s\n" "$key" "disable $desc"
+            indent="  "
         else
-            if [[ "${_dick_alias_only[$key]}" != "true" ]]; then
+            if [[ "$(eval "echo \$_dick_alias_only_${key/-/_}")" != "true" ]]; then
                 printf "  --use-%-20s %s\n" "$key" "enable $desc"
                 desc=""
                 indent="  "
             fi
-            for flag_alias in "${(@k)_dick_args_alias}"; do
-                if [[ "${_dick_args_alias[$flag_alias]}" == "$key" ]]; then
-                    if [[ ! -z $indent ]]; then
-                        printf "%s  %3s%-21s %s\n" "$indent" "${flag_alias}" "" "$desc"
-                    else
-                        printf "  %-26s %s\n" "${flag_alias}" "$desc"
-                        indent="  "
-                    fi
-                    desc=""
+            flag_aliases="$(eval "echo \$_dick_args_alias_${key/-/_}")"
+            for flag_alias in $flag_aliases; do
+                if [[ ! -z $indent ]]; then
+                    printf "%s  %3s%-21s %s\n" "$indent" "${flag_alias}" "" "$desc"
+                else
+                    printf "  %-26s %s\n" "${flag_alias}" "$desc"
+                    indent="  "
                 fi
+                desc=""
             done
-            echo
         fi
+        echo
     done
 fi
